### ISSUE TITLE
n_cells and n_valid_cells

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#106]
@imagirom @constantinpape 
I usually have two columns `n_cells` and `n_valid_cells` (i.e. the ones that passed cell-based QC). The first contains all cells and is useful for image based QC (too many cells, i.e. overgrown). The latter is useful to see how many cells were actually entering the analysis. What do you think?

**Comment by constantinpape** [comment]
We have this already, but I think it's just not copied into the default tables.
I will fix it later once you have pushed the new viewer version, so that I can double check this on my own.

**Comment by constantinpape** [comment]
@tischi  We will have `n_cells` and `n_outlier_cells` in the default tables soon. With `n_cells_total = n_cells + n_outlier_cells`.

**Comment by constantinpape** [comment]
Implemented in #107
