### ISSUE TITLE
Cannot report issue from the Plate Viewer

### ISSUE THREAD

**Issue by wolny** [hci-unihd/batchlib#113]
I'm using the latest version of the plugin, generated my dedicated github access token, but when trying to create an issue for a given image I get '404 Not Found'.
![Screenshot from 2020-05-11 17-29-27](https://user-images.githubusercontent.com/706781/81580260-82b8dd00-93ad-11ea-9573-f6494589ed07.png)

**Comment by tischi** [comment]
Not sure... 
Maybe something wrong with your token?

"Typically, we send a 404 error when your client isn't properly authenticated. "

You could post your token in Slack and then I could test.

**Comment by wolny** [comment]
So I tried with a random token as well, then it's correctly 401 Not Authenticated. I'll share the token with you. Thx

**Comment by tischi** [comment]
```
404 Not Found
Status: 404 Not Found
X-Accepted-OAuth-Scopes: 
Server: GitHub.com
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-RateLimit-Reset: 1589268705
Date: Tue, 12 May 2020 07:05:50 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: deny
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
X-RateLimit-Remaining: 4990
X-GitHub-Media-Type: unknown, github.v3
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-RateLimit-Limit: 5000
X-XSS-Protection: 1; mode=block
Content-Length: 117
X-OAuth-Scopes: 
X-GitHub-Request-Id: F2A3:41157:79EE86D:8CE75BA:5EBA4ACD
Content-Type: application/json; charset=utf-8
```

1. Did you check all of those guys?
![image](https://user-images.githubusercontent.com/2157566/81649175-306cd000-9430-11ea-830e-852e16644445.png)

2. @constantinpape does @wolny have the same rights on the antibody-isssues repo as I?

**Comment by constantinpape** [comment]
![Screenshot from 2020-05-12 11-09-28](https://user-images.githubusercontent.com/4263537/81665535-1b4c6d00-9441-11ea-8630-6c36211b8a48.png)

@wolny should be a member of the ial team, so he should have even more permissions than you.

**Comment by wolny** [comment]
Hey @tischi, it's all good now. It seems to be a problem with my access token. Cheers!
