### ISSUE TITLE
patient_type missing in DB for some plates

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#116]
@wolny @constantinpape 

1. I guess I cannot assume that the `patient_type` column exists for all plates?!

![image](https://user-images.githubusercontent.com/2157566/81652341-e1289e80-9433-11ea-8b18-19e222b7b646.png)

**Comment by wolny** [comment]
Hey @tischi, yes `patient_type` is present only in those wells which were marked in the excels by Vibor. Those are not are.
