### ISSUE TITLE
Finalize QC

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#125]
I just discussed with @tischi: we should finalize the values for the QC that is currently implemented:
- cell sizes: for this, @tischi will plot histograms for a large enough samples of cells; we try to estimate a threshold based on this, but will double check if it makes sense by exporting masks that show all cells that would break it and then see how these cells actually look.
- nucleus sizes: as discussed it would make a lot of sense to filter nucleus sizes to get rid of small and large dirt. This is implemented already, but not activated yet. For this, @metavibor suggested values already. I think we can also just set a lower and upper radius for and compute this analytically, because the nuclei are fairly uniform in size. I will try this later and then see how this agrees with the values proposed by vibor.
- fraction of control cells per well: I think this is an important QC measure, but I don't have a good idea how to set it. @metavibor, @tischi do you have any more insights here?

**Comment by metavibor** [comment]
> fraction of control cells per well: I think this is an important QC measure, but I don't have a good idea how to set it. @metavibor, @tischi do you have any more insights here?

I would go the same way as you described above. Lets plot histograms of control cell numbers per well and see what is the lowest number we get and than check those wells and the values we get in them to see if something is weird... that should give us a clue of the good value there

**Comment by constantinpape** [comment]
> I would go the same way as you described above. Lets plot histograms of control cell numbers per well and see what is the lowest number we get and than check those wells and the values we get in them to see if something is weird... that should give us a clue of the good value there

Ok, sounds good.
@tischi you should have all the information for this in the tables.

**Comment by tischi** [comment]
I'll be making one issue per QC in the antibody-issues repo and post the plots there.
I also made a new issue tag "quality control" for this.

**Comment by tischi** [comment]
@metavibor @constantinpape 
ok, I think I did what I can do for now without discussing with you guys:
- https://github.com/hci-unihd/antibodies-analysis-issues/issues/82
- https://github.com/hci-unihd/antibodies-analysis-issues/issues/81

**Comment by constantinpape** [comment]
This is done now, here are the criteria we will use for the preprint:
```
CELL_OUTLIER_CRITERIA = {'max_cell_size': 12500,
                                                   'min_cell_size': 250,
                                                   'min_nucleus_size': 125,
                                                   'max_nucleus_size': 1000}

IMAGE_OUTLIER_CRITERIA = {'max_number_cells': 1000,
                                                     'min_number_cells': 10} 

WELL_OUTLIER_CRITERIA = {'min_number_control_cells': 100,
                                                   'min_fraction_of_control_cells': None,
                                                   'check_ratios': True}
```
