### ISSUE TITLE
Cell tables: add cell anchor

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#128]
@constantinpape 
Since we are also now looking at single cell stuff, I think it would be very useful to have `anchor_x` and `anchor_y` coordinates in the cell tables (both in the hdf5 and the excel tables).
Would that be possible to add?

**Comment by constantinpape** [comment]
Sure, no problem. Will add it in the next run.

**Comment by constantinpape** [comment]
@tischi this is pretty easy to implement.
In the h5 tables, I will just have another table for the cell segmentation called `properties`
which contains cell sizes, anchors and could be extended with other, intensity independent, attributes.

Would you also want this to be exported to the excel tables I produce for you?
In there, I would probably not export an extra table, but just add it to the cell tables that are already exported. What do you think?

**Comment by tischi** [comment]
> In the h5 tables, I will just have another table for the cell segmentation called properties
which contains cell sizes, anchors and could be extended with other, intensity independent, attributes.

makes sense

> Would you also want this to be exported to the excel tables I produce for you?
In there, I would probably not export an extra table, but just add it to the cell tables that are already exported. What do you think?

Just one table is much easier for me. In fact, also in the hdf5 just having one table would be more convenient, I think.

**Comment by constantinpape** [comment]
> Just one table is much easier for me. In fact, also in the hdf5 just having one table would be more convenient, I think.

In the hdf5 that is not a good idea due to the way we compute these things; this should all stay modular!

For the export, no problem.

**Comment by constantinpape** [comment]
Implemented in #130, but I still need to add it to the excel tables, will do tomorrow.

**Comment by constantinpape** [comment]
@tischi this is all implemented now; the new excel cell tables will have columns `anchor_x` and `anchor_y`.
