### ISSUE TITLE
Finalize exporting of score table

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#132]
We need to export a final clean excel table with results from our analysis and cohort ids + elisa results.
This is already implemented here: https://github.com/hci-unihd/batchlib/blob/master/batchlib/reporting/export_tables.py#L197

However, we still need to fix the following things:
- [x] Filter score names properly
- [x] Rename scores to be more succinct 
- [x] Fix how the data from the DB is read (currently all DB results are blank and there are no proper warnings if we don't have DB values)
- [x] Add the missing cohort information and elisa results to the DB (@metavibor has posted this to the slack already)

@wolny I will take care of the first two points, could you take care of the last two?

**Comment by wolny** [comment]
> Fix how the data from the DB is read (currently all DB results are blank and there are no proper warnings if we don't have DB values)

This has been fixed today

> Fix how the data from the DB is read (currently all DB results are blank and there are no proper warnings if we don't have DB values)

tackled in https://github.com/hci-unihd/batchlib/pull/133

**Comment by constantinpape** [comment]
Should all be fixed now.
