### ISSUE TITLE
Adapt plot function to IgM; make sure that outliers are marked correctly

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#142]
There are two issues with the plot function for the new plates with IgM serum:
- We should use the same colormap as for IgG, so I copied it, see https://github.com/hci-unihd/batchlib/blob/master/batchlib/util/plate_visualizations.py#L347-L363. However it looks quite different, see plots below.
- It looks like the outlier marking does not work quite as expected; the outliers for IgG are also marked for IgM, again see the plots.

@imagirom could you have a look into this?
![plate1_IgM_20200527_125952_707_IgG_ratio_of_median_of_means_per-well](https://user-images.githubusercontent.com/4263537/83640922-1ba5d700-a5ad-11ea-88b2-acbbcbab6759.jpg)
![plate1_IgM_20200527_125952_707_IgM_ratio_of_median_of_means_per-well](https://user-images.githubusercontent.com/4263537/83640934-1e083100-a5ad-11ea-97e2-213d0328c492.jpg)

**Comment by imagirom** [comment]
Sure, I will look into it. The colormap that is used currently for IgM is the default one, so I suspect that the column name for IgM is somehow different in the table.

**Comment by constantinpape** [comment]
> Sure, I will look into it.
Thanks!

> The colormap that is used currently for IgM is the default one, so I suspect that the column name for IgM is somehow different in the table.

Ok, maybe that also explains why the outlier matching goes wrong.

**Comment by imagirom** [comment]
@constantinpape Regarding the outlier marking: I checked the result table of the plate you posted the plots of, and the markings seem to reflect what is in there: The columns `IgG_outlier_type` and `IgM_outlier_type` have identical values (as well as the corresponding `is_oulier` columns).
Hence I think this is either just correct or the Issue lies somewhere else..
(Disclaimer: I have not fixed the colorbar Issue yet. But I currently do not see how that would be connected)

**Comment by constantinpape** [comment]
> Hence I think this is either just correct or the Issue lies somewhere else..

It's definitely not correct, but probably goes wrong when I copy this to the summary table.
I will check it out.

**Comment by imagirom** [comment]
@constantinpape No, I think it is not an Issue in table merging. I just checked and the values of the `is_outlier` and `outlier_type` columns are already identical in the per serum tables at `tables/IgX`.

**Comment by constantinpape** [comment]
That is weird, I just checked locally and the intensity outliers were not triggered for IgM.
In any case, I will have a look.

**Comment by imagirom** [comment]
Ok.. maybe I am not looking at the right tables. Please tell me if you see something contradicting my observations.

**Comment by constantinpape** [comment]
This should be fixed now. I will check it in the new results tomorrow and then close this.
