### ISSUE TITLE
Site Name

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#15]
@constantinpape 

I am adding a new column to the table called `site-name`

![image](https://user-images.githubusercontent.com/2157566/79075337-8ac02700-7cf2-11ea-847b-0e58e4979360.png)

I construct this from the image name in the table. I need this for the communication of the table view and the image view. It is like the `label` column in the PlatyBrowser. So if you could add this column already when you create the table that would be nice (in case you agree on this).

**Comment by constantinpape** [comment]
> I construct this from the image name in the table. I need this for the communication of the table view and the image view. It is like the `label` column in the PlatyBrowser. So if you could add this column already when you create the table that would be nice (in case you agree on this).

Sounds good, I will add it.

**Comment by constantinpape** [comment]
I added functionality to write tables in this format:
https://github.com/hci-unihd/batchlib/blob/master/batchlib/analysis/summary.py

See also #30
