### ISSUE TITLE
Write analysis summary for plate-viewer

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#30]
As discussed, we should write summary tables and image representations so that it can be inspected visually (e.g. with the fiji-plateViewer).
So far, we have discussed the following:
- Write an image with a mask for the cells classified as infected / not infected
- Write images with the mean intensities of serum and marker per cell
- Write succinct summary of analysis in `ImageInformation` / `WellInformation` hdf5 attributes
- Write a table with all relevant things from the analysis pipeline

I have added a skeleton job to do this already, now we only need to scrape the data from the analysis and write it in there:
https://github.com/hci-unihd/batchlib/blob/master/batchlib/analysis/summary.py

cc @tischi

**Comment by tischi** [comment]
Regarding well-based measurements I would for now add them to the image table. Then all images in the same well would have the same number in such columns, which is redundant, but also supporting a well-based table is out-of-scope for me at the moment.

**Comment by imagirom** [comment]
On the cell-level side this is now mostly implemented, apart from
> * Write succinct summary of analysis in `ImageInformation` / `WellInformation` hdf5 attributes
What did you have in mind for this?

**Comment by constantinpape** [comment]
> What did you have in mind for this?

I think this should be the most relevant score on a per image / per well level.

**Comment by tischi** [comment]
...maybe, since we now have the interaction with the table working the `WellInformation` and `ImageInformation` fields are less important?

**Comment by constantinpape** [comment]
> ...maybe, since we now have the interaction with the table working the `WellInformation` and `ImageInformation` fields are less important?

Yep, that's true. It's more important in cases where there's no table. Wouldn't hurt to add it though.
(And the plateViewer should def. keep the functionality.)

**Comment by tischi** [comment]
Yes, I'll keep it!

**Comment by tischi** [comment]
@imagirom 

1. What is the number that Vibor currently looks at when you send him the Excel sheets with the analysis? I guess it is a well-based number? This number should be in the one in the `WellInformation`
2. Could you please also add this number to the image table?

**Comment by constantinpape** [comment]
> * What is the number that Vibor currently looks at when you send him the Excel sheets with the analysis? I guess it is a well-based number? This number should be in the one in the `WellInformation`
> 
> * Could you please also add this number to the image table?

I think that this number is the `cell_based_score` we have in the table.
I agree, we should also write the well score in the table, and then maybe write the main Image/Well Scores into the `ImageInformation`/`WellInformation` attributes.

**Comment by imagirom** [comment]
The number I report to Vibor currently it is the median over the `cell_based_score` of the images of the well, for now it is in the table under `well_cell_based_score`.

The `ImageInformation/WellInformation` you proposed make sense, but I will not add it right now, as it does not seem to be that urgent. Please tell me if you want to use it in the viewer now, then I will add it.

**Comment by tischi** [comment]
> The ImageInformation/WellInformation you proposed make sense, but I will not add it right now, as it does not seem to be that urgent. Please tell me if you want to use it in the viewer now, then I will add it.

It's fine, no need to rush anything!

**Comment by constantinpape** [comment]
This has been superseded.
