### ISSUE TITLE
Image storage compression

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#33]
@constantinpape 
Just an interesting observation: the segmentation images load **much** faster than the fluorescence channels, indicating that the compression makes a big difference. Is there anything we can do to compress the fluorescence channels even more?

**Comment by constantinpape** [comment]
> Just an interesting observation: the segmentation images load **much** faster than the fluorescence channels, indicating that the compression makes a big difference.

Yeah, I think that is not very surprising. Segmentations are probably a few kb only.

> Is there anything we can do to compress the fluorescence channels even more?

Actually yes, we could cast them back to be 16bit (or even 8bit).
However, this might have some impact on the analysis code by @Steffen-Wolf and @imagirom.

**Comment by tischi** [comment]
But, we also need the raw data in a sense that they need have the exact same pixels values as when you would open the *.tif files in ImageJ! This is crucial for discussing background subtraction issues. Do we have this right now, i.e. is this the current "raw"?

**Comment by constantinpape** [comment]
> ok, maybe then there is not so much we can do...

Let's see how it's working with multi-scale and then look if we need to improve this further.

**Comment by constantinpape** [comment]
I think we cannot do much better than right now without investing much effort / making the file format less portable, so I will close this for now.
