### ISSUE TITLE
Multiscale images

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#35]
@constantinpape 
Just to keep track of when the multi-scale images will be generated by the pipeline.
Currently they are not yet, right?

**Comment by constantinpape** [comment]
> Just to keep track of when the multi-scale images will be generated by the pipeline.
> Currently they are not yet, right?

Multi-scale images are generated by the pipeline since e26132369. Most plates processed on the hci server has been started before that was merged, but for all future plates we will have it.

**Comment by tischi** [comment]
@imagirom Could you run the titration plate with such a pipeline (see above)?

**Comment by constantinpape** [comment]
Recomputation is done.

**Comment by tischi** [comment]
@constantinpape 
This one is still singe scale: data-processed-seg-new/titration_plate_20200403_154849
Maybe other folder?

**Comment by constantinpape** [comment]
> This one is still singe scale: data-processed-seg-new/titration_plate_20200403_154849
> Maybe other folder?

please read in slack for details, I posted the new path there

**Comment by constantinpape** [comment]
Can you load the mult-scale now?
Do you think it's working properly?

**Comment by tischi** [comment]
I can load it, but the shift between the different resolutions somehow got worse...
Do you want to quickly zoom?

**Comment by constantinpape** [comment]
> I can load it, but the shift between the different resolutions somehow got worse...
Is it still the same problem as before?

> Do you want to quickly zoom?
Should we talk this afternoon after you showed the viewer to the others?

**Comment by constantinpape** [comment]
These are the down-sampled sizes I produce:
```
/serum                   Group
/serum/s0                Dataset {930, 1024}
/serum/s1                Dataset {465, 512}
/serum/s2                Dataset {232, 256}
/serum/s3                Dataset {116, 128}
``
This is the down-sampled sizes from BDV:
```
/t00000/s02/0            Group
/t00000/s02/0/cells      Dataset {1/Inf, 930/Inf, 1024/Inf}
/t00000/s02/1            Group
/t00000/s02/1/cells      Dataset {1/Inf, 465/Inf, 512/Inf}
/t00000/s02/2            Group
/t00000/s02/2/cells      Dataset {1/Inf, 232/Inf, 256/Inf}
```

So the sizes in x and y are the same.
But is there maybe a problem in your code due to the singleton z axis?

**Comment by tischi** [comment]
I think I fixed it. It was the issue that I suspected with tiling many of them.

Something else, could do downsample even one more time? If think when zooming out to see the whole plate this may help somewhat.

**Comment by constantinpape** [comment]
> Something else, could do downsample even one more time? If think when zooming out to see the whole plate this may help somewhat.

Sure, no problem.

**Comment by constantinpape** [comment]
So I think this is fixed now. Closing the issue for now, feel free to reopen if anything else is coming up.
