### ISSUE TITLE
Analysis: Fraction infected

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#37]
@imagirom 
I think having a column "fraction_infected" would be useful.

**Comment by imagirom** [comment]
That would be just `num_infected_cells/num_cells` or would you like to know the fraction of pixels that belong to infected cells?

**Comment by tischi** [comment]
No, just `num_infected_cells/num_cells`.  I think this is important to have quick access to, especially for the titration plate, because, afaik, this was the main point to figure out how we could get to 0.5 (50%).

**Comment by imagirom** [comment]
I have added the column (see 30c2f512eb70b8ae759fdf2866ce442f8424b688). Should I rerun the analysis now? That will make data-processed-multiscale/titration_plate_20200403_154849/analysis.csv unavailable for a couple of minutes

**Comment by constantinpape** [comment]
We have this now. I will rerun everything with new settings either on Sunday or Monday on EMBL servers and then we can check it.
