### ISSUE TITLE
Storing tables in hdf5

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#39]
As discussed today, we may want to store tables associated with (segmentation) images for a given image in the hdf5.
For example, we could have a table for the cell segmentation image that stores the values measured per cell.

I would suggest to store the tables like this in the hdf5:
```
/tables
  /cell_segmentation (or other dataset-name)
```
`tables/cell_segmentation` would just be a 2d dataset storing the table.
We would store the column names in the attribute `columns`.
The first column should always be `label_id`(i.e. the id of the corresponding object in the segmentation).

One potential I see is storing values that are not floats.
While this is possible in hdf5, see http://docs.h5py.org/en/stable/strings.html#fixed-length-ascii.
I don't know how easy this would be to read in java, and I don't think that mixed data-types are possible. Hence if one column has strings then all need to be string and when loading the table one needs to check whether the values are actually numeric.

Let me know what you think @imagirom @tischi @Steffen-Wolf

**Comment by imagirom** [comment]
I am not sure.. If reading this in java would work fine, the key question would probably be how big of a disadvantage not having access to mixed data-types is.
If we decide to do it within the h5, I would go for it as you proposed.

**Comment by tischi** [comment]
My code anyway assumes that all column values are Strings initially, this is the easiest, because so far I exclusively read columns from text files.
And then at some point later in the code I am doing this:
```
private static Class getColumnType( String string )
	{
		try
		{
			Double.parseDouble( string );
			return Double.class;
		}
		catch ( Exception e2 )
		{
			return String.class;
		}
	}
```

**Comment by constantinpape** [comment]
> My code anyway assumes that all column values are Strings initially, this is the easiest, because so far I exclusively read columns from text files.
> And then at some point later in the code I am doing this:

Ok, then I will implement it and just store everything as string.

**Comment by constantinpape** [comment]
@tischi I uploaded an example table, it's in `tables/data`
https://oc.embl.de/index.php/s/0EfbFxVsfZkJKE6

Can you check if you can load it?

**Comment by tischi** [comment]
@constantinpape 
Can you post here python code how you read it?

**Comment by tischi** [comment]
Do you have an idea how to fix this?
```
final String[] columns = hdf5Reader.string().getArrayAttr( "/tables/data", "columns" );

Exception: Attribute columns of object /tables/data needs to be a String array of rank 1.
```

**Comment by constantinpape** [comment]
Here is the code to read / write the table in python:
https://github.com/hci-unihd/batchlib/blob/master/batchlib/base.py#L348-L384
(The argument `f`is what's being returned by `h5py.File`)

Regarding the error you are seeing: yes, I have an idea:
It seems like the strings in attributes also need to be encoded properly to be portable, see
http://docs.h5py.org/en/stable/strings.html#fixed-length-ascii

I will update this later and then upload a new example file.

**Comment by constantinpape** [comment]
Here's a new example file:
https://oc.embl.de/index.php/s/COkIpaaQcUvWnXv

**Comment by tischi** [comment]
Still same error.

**Comment by tischi** [comment]
Maybe don't make it an attribute but a proper data array as well?

**Comment by constantinpape** [comment]
Makes sense. I will upload a new version later.

**Comment by constantinpape** [comment]
And here is the new version:
https://oc.embl.de/index.php/s/GlzrbKuXQGjzti7

**Comment by tischi** [comment]
Perfect. Nice and easy (for Java standards 😄 ):
```
final String[] columns = hdf5Reader.string().readMDArray( "tables/data/columns" ).getAsFlatArray();
final String[] cells = hdf5Reader.string().readMDArray( "tables/data/cells" ).getAsFlatArray();
```

**Comment by constantinpape** [comment]
Ok, great I will look into porting the analysis task so that we use this instead of the extra pickle files.

**Comment by constantinpape** [comment]
Also done.
