### ISSUE TITLE
FileLock racing issues

### ISSUE THREAD

**Issue by Tomaz-Vieira** [hci-unihd/batchlib#4]
I see that you have your own implementation of FileLock instead of using the native `fcntl.lockf`. I believe the current implementation is racy:

```python3                                                                                                                     
    def __enter__(self):
        # no lock when entering the function, so 2 threads/process can enter at once     
        if os.path.exists(self.path):
            self.wait_for_unlock()
        # another thread/process can create the file at this point, since nothing is locked yet
        with open(self.path, 'w'): # lockfile then gets overwritten here
            pass
         #at this point, two threads are running simultaneously
                                                      
    def __exit__(self, type, value, traceback):
        os.remove(self.path)
        # since two threads "acquired" the lock,
        # one of them will fail trying to delete the file
```

`fcntl.lockf` will have the kernel ensure thread-safety for you, but I think it's limited to posix and I'm also not sure if it's supported in distributed filesystems like the typical GPFS's we find in clusters.

**Comment by constantinpape** [comment]
Thanks for catching this!
I will see if I can change to `fcntl.lockf` easily.

**Comment by constantinpape** [comment]
Ok, I had a bit closer look and I think I can do the following:

I need the pattern
```
with FileLock(some_lock_file) as :
    do stuff
```
that delays starting the code in the with stating until the lock is released.
I couldn't find `__enter__` or `__exit__` methods for `lockf` (which just wraps a system call I guess), 
so I cannot use it directly. 

I could use it in the `FileLock` implementation though. `lockf` throws an `OSError` if the lock fails. So ths should work:
```
while True:
      try:
            f = open(some_lock_file, 'w')
            fcntl.lockf(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
            break
       except OSError
           sleep(10)

```
I think this should remove racyness, correct?

**Comment by constantinpape** [comment]
Interesting, look what I found :D
https://github.com/ilastik/lazyflow/blob/master/lazyflow/utility/fileLock.py

**Comment by constantinpape** [comment]
This does more or less the same thing as I did though and unlinks the lock:
https://github.com/ilastik/lazyflow/blob/master/lazyflow/utility/fileLock.py#L162
So I am not sure if it removes the racyness.

Also, `lockf` is only posix and doesn't work for some distributed filesystems (I actually investigated this on the c/c++ side a while ago for z5), so I don't think it's a good solution.

**Comment by Tomaz-Vieira** [comment]
Aha, nice findings there! So, it's almost the same as what you're doing, but it does the create_if_there_is_no_file in a single shot, since (at least on linux)  `open()` is guaranteed to be atomic. I'm still not sure if this is guaranteed on GPFS, but it already looks better than `lockf`, indeed =)

**Comment by constantinpape** [comment]
switched to lazyflow impl, thanks for raising this!
