### ISSUE TITLE
Initially visible channels

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#42]
@constantinpape @metavibor

Since, after the analysis, we have many channels (segmentations a.s.o), I was wondering which ones of them should be visible by default ("initiallyVisible" attribute). Currently none of them is, but for my viewer at least one of them must be for the initialisation. I think a natural choice may be all the "raw" channels that were acquired?

Any opinions?

**Comment by constantinpape** [comment]
> I think a natural choice may be all the "raw" channels that were acquired?

Yes, I agree. It's easy for me to activate this. 
The other option would be to show the corrected channels by default.

btw, the hdf5 attribute is called `visible` not `initiallyVisible`.

**Comment by tischi** [comment]
ok! Let's wait what @metavibor thinks...

**Comment by metavibor** [comment]
are we talking about the uneven illumination correction? If yes than I would prefer to see corrected images by default.... uneven illumination pattern bothers me... maybe there will be some rare cases where the correction produced something unexpected and than we can check the "rawest" data but in general should not be a problem

**Comment by constantinpape** [comment]
> If yes than I would prefer to see corrected images by default....

makes sense, I will adapt it.

**Comment by constantinpape** [comment]
Will be fixed in #46

**Comment by constantinpape** [comment]
This is fixed now.
