### ISSUE TITLE
Analysis table name

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#43]
@imagirom @constantinpape 

Did you guys settle on a name for the table such that I can load it automatically?

**Comment by imagirom** [comment]
No, not yet. What about `platedir_analysis.csv` with `platedir` being the name of the folder the table is in (e.g.`20200406_222205_911_analysis.csv`)?

**Comment by constantinpape** [comment]
> `20200406_222205_911_analysis.csv`

This is implemented on master already since #40

**Comment by tischi** [comment]
And should I assume that `20200406_222205_911` must be identical to the parent folder name?

**Comment by constantinpape** [comment]
> And should I assume that `20200406_222205_911` must be identical to the parent folder name?

yes (or at least it will be by default, it's still possible to over-ride this)

**Comment by imagirom** [comment]
> > `20200406_222205_911_analysis.csv`
> 
> This is implemented on master already since #40

Whoops, sorry for missing that

**Comment by constantinpape** [comment]
> Whoops, sorry for missing that

No worries, anyway closing this for now.
