### ISSUE TITLE
Add columns to table

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#47]
@constantinpape @imagirom 

Could you please add two columns to the table?
`file-name`
`well-name`

**Comment by imagirom** [comment]
Sure. `well-name` as e.g. `A05`?

**Comment by tischi** [comment]
Yes, please!

And do you also have the `cell-based-score` as one number per **well**? I guess this is what Vibor is looking at in the end, isn't it? If so, it would be important to have those numbers in the tables as well. I know they would be the same for all the images in one well, but that's fine. Maybe call it `well-cell-based-score`. We could have it as a convention that all columns that start with `well-` contain well based information.

**Comment by constantinpape** [comment]
> Could you please add two columns to the table?
> `file-name`

We have the column `image` already, which contains the file name. If you want, we can rename it to `file_name`.

> well-name

This is included in `site-name`, which is composed as following:
`<WELL_NAME>-<NR OF IMAGE IN WELL>`

If you want we can change how this is formatted, but I don't think we should add more columns, because they would be completely redundant.

> Maybe call it `well-cell-based-score`. We could have it as a convention that all columns that start with `well-` contain well based information.

Yes, I think this makes sense. I think @imagirom is using the median of images in the well for this right now; but as we have discussed it might make sense to use the median over all cells in the well instead.

**Comment by imagirom** [comment]
I just added the `well_cell_based_score` in a20f4298390acb75fa5104e53904bd09fa615b95, which for now is indeed the median over (non-outlier) images.

**Comment by tischi** [comment]
It is just handy to have a well-name column, because then one can colour all data points that belong to the same well in the same colour, which is often useful to see how consistent the measurements are across the different images in the same well. But we could also just have the `image` column stored and then I can add all deduced columns, such as `well-name` and `site-name` on the fly while loading.

we should for sure add a column that reflects the current "score".

**Comment by imagirom** [comment]
> we should for sure add a column that reflects the current "score".

What exactly do you mean by that? The `cell_based_score` is the current per-image score of the cell-level analysis, the `well_cell_based_score` the per-well one.

**Comment by tischi** [comment]
@imagirom I did not see your answer, yet. So that's fine! 

Ideally there would also be some quick way to know how our current score is computed, maybe some link to some github issue somewhere? Such that one does not have to rely on asking you personally ;-)

**Comment by constantinpape** [comment]
> But we could also just have the `image` column stored and then I can add all deduced columns, such as `well-name` and `site-name` on the fly while loading.

Ok, let's leave it at the current `image` and `site-name` columns, and you can deduce anything else from this on the fly.

> Ideally there would also be some quick way to know how our current score is computed, maybe some link to some github issue somewhere?

That's a good point, but I am not quite sure what's the best way to do this. Personally, I would not go with issues but rather have a section in the readme.

**Comment by tischi** [comment]
> Personally, I would not go with issues but rather have a section in the readme.

Yes, sounds better!

**Comment by imagirom** [comment]
I agree, and will add that soon. Maybe additionally we could somewhere log the current commit hash of batchlib when the analysis is run?

**Comment by constantinpape** [comment]
> Maybe additionally we could somewhere log the current commit hash of batchlib when the analysis is run?

See #48 ;).

**Comment by constantinpape** [comment]
Superseded by more recent discussions.
