### ISSUE TITLE
Compute median plate background

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#53]
@imagirom 

Could you please
- [x] compute the median background in all pixels that are not cells
- [x] add this number to the image table

**Comment by imagirom** [comment]
Added in c1838f2bf0ad530eb670987fda4ebf0900b0d708, to the image-wise and well-wise tables. The columns are `plate_bg_median_serum` and `plate_bg_median_marker`. I also added the well-wise medians under `well_bg_median_serum` and `well_bg_median_marker` as well as all respective MADs (replace `median` with `mad` in the column names).
