### ISSUE TITLE
Compute image background value

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#54]
@imagirom 

Could you please
- [x] compute the median background in all pixels **in each image**
- [x] add this number to the image table

**Comment by imagirom** [comment]
Added in c1838f2bf0ad530eb670987fda4ebf0900b0d708. The columns in the table are `image_bg_median_serum` and `image_bg_median_marker`. I also added the respective MADs under `image_bg_mad_serum` and `image_bg_mad_marker`.
