### ISSUE TITLE
Compute background corrected ratio score

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#55]
@imagirom 

Could you please 

- [x] compute (i) for each well and (ii) for each image:

```
( median( serum )_infected_cells - plate_serum_background ) /  ( median( serum )_not_infected_cells - plate_serum_background )
```

and 

- [x] add both values to the image and well table

**Comment by imagirom** [comment]
I will do this after #69 is addressed

**Comment by imagirom** [comment]
@tischi I assume that with `( median( serum )_infected_cells - plate_serum_background )` you mean the median over all infected cells of the per-cell median serum activations. Is that correct?

**Comment by imagirom** [comment]
I added the background subtraction in `7a5f021ef36f889829755d3a5bc5018c588a4226`. This is now the main score that can be found either as `score` or `ratio_of_median_of_means` in both tables.
