### ISSUE TITLE
More values for outlier detection

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#56]
Currently, we only have `True` and `False` as values in the outlier detection.
This is bad, because `False` could either mean that the image is not an outlier, OR that there is no outlier detection for it yet.
We should change to `True`, `False` or `None`.
I can do it, but I will wait till @imagirom finishes cleaning up the code.

cc @wolny

**Comment by wolny** [comment]
Hey @constantinpape very good point! It should be a quick fix, i.e. instead of taking a default predictor which returns `False` (if there is no outlier detection for the plate), it should return `None` instead. I'll put that in my quick PR

**Comment by tischi** [comment]
I think should also 

- [ ] add another column specifying what and who determine the outlier, i.e. `outlier-type`. I would make it a `String` where there could be keys such as `manual_vibor`, `too_high_background`, `automated_debris`, ...

**Comment by constantinpape** [comment]
> Hey @constantinpape very good point! It should be a quick fix, i.e. instead of taking a default predictor which returns `False` (if there is no outlier detection for the plate), it should return `None` instead. I'll put that in my quick PR

Ok, that's good. Thanks!

**Comment by constantinpape** [comment]
@tischi 
Yes, that's a very good point too.
Let's fix the three value issue first and then think about how we manage the `outlier-type`
