### ISSUE TITLE
Covid project database

### ISSUE THREAD

**Issue by wolny** [hci-unihd/batchlib#58]
Currently lots of data related to the project is spread around the HCI servers, our repositories and external files and we need to bring those data in sync and store it in a centralized database which can easily be updated from within Plate Viewer, batchlib jobs, QC app or directly.

The following information should be stored inside a DB:
- plates metadata
- results from our analysis pipeline
- quality control information (outliers)
- manual assessments about positive/negative samples from Vibor
- results from the Neutralization Assay (TBD)

Since we're still in the development phase and what we want and don't want to store is still evolving I'd suggest setting up a schema-less database (which will give us the necessary flexibility), importing the data and results we currently have and provide an API based access to the database from within batchlib and Plate Viewer.

More specifically I'd choose the MongoDB data store, as it's very easy to use both directly (CLI) and from the Java/Python API. We would need the following:
1. Setup MongoDB primary instance on one of our servers (ideally directly on EMBL premises, so we won't have to migrate from HCI to EMBL)
2. (optionally) setup MongoDB secondary (replica) on another VM to prevent data loss
3. Decide how the information should be stored initially in MongoDB (i.e. collection names and attributes)
4. Write an initial migration script to populate the collections (btw a 'collection' is where MongoDB stores object/documents) 
5. Write a simple API to be able to update the collections from within the Plate Viewer (java), Outlier Tagger app (python), batchlib workflows (python).

The most important point for now is 3. Here's my suggestion for the initial collections of documents and their attributes (I skip the `id` filed which will be created automatically by MongoDB):
1. `immuno-assay-analysis-results`  - a collection to store results from our analysis pipeline
Document attributes: `created_at`, `finished_at` (optional, but useful if we want to monitor the execution duration), `workflow_name`, `plate_name` (same as `name` in `assay-plates` collection), `batchlib_version`, `status`, `result_table`, `well_result_table`, `image_result_table`, `object_result_table`
2. `immuno-assay-metadata` - a collection to store all metadata associated with the plates we have so far
Document attributes: `created_at`, `name`, `qc_status` (there might be cases where we want to skip entire plate as suggested by @tischi) `channel_mapping`, `wells` (nested array; attributes: `name`, `qc_status`, `images`, `manual_assessment` (i.e. positive/negative)), `images` (let's keep it as a nested array of documents within the `wells` objects; normally this would be a separate collection in order to increase the query efficiency, but it would make things easier for us this way). The attributes of a single `image`: `name`, `well_name`, , `qc_status` (outlier or not), `outlier_type`, `inst_seg_gt` (whether we have an inst seg GT for this image), `sem_seg_gt` (whether we have a sem seg GT for this image), `issue_urls` (links to the issues if any)
3. `neutralization-assay` - TBD

CC @constantinpape @tischi @Steffen-Wolf @imagirom @lorenzocerrone 
Please comment if you think we need some more info in our database.

**Comment by constantinpape** [comment]
Thanks for looking into this @wolny, this sounds very good already.

From my side, there is just a few minor things:
- I think the "top-level names" are a not very clear, maybe `immuno-assay-analysis-results` for 1. and `immuno-assay-metadata` for 2. ?
- For 1., it should be possible to have separate entries for a plate for different batchlib commits, in order to keep track of how results evolve (I guess that should be relatively easy in the design you propose).
- Also for 1., we will have multiple `result_tables`: We will at least have 1 image table and 1 well table, see also #59. There will also be object based tables (1 for each image), but I am not quite sure yet if these need to go into the database. In addition, @imagirom might run additional kinds of analysis that generate different versions of the tables (but this could also be handled by pushing this to different `antibody-assays` entries, see previous point).

**Comment by tischi** [comment]
I am not sure you cover this already in above schema, but I think for the antibody-assay we may need those granularities: 

- plates
- wells
- images
- cells 

(see also here: https://github.com/hci-unihd/batchlib/issues/59)

For example, the QC can be image and well based. 
Excluding one image would still allow to compute a score for a well, but excluding a whole well would automatically render all images in the well invalid. 
And the QC could also be plate based: sometimes one decides a whole plate should not be analysed due to some reasons.

**Comment by wolny** [comment]
Thanks for your comments @constantinpape and @tischi.
@constantin:
> I think the "top-level names" are a not very clear, maybe immuno-assay-analysis-results for 1. and immuno-assay-metadata for 2. ?

agreed!

> For 1., it should be possible to have separate entries for a plate for different batchlib commits, in order to keep track of how results evolve (I guess that should be relatively easy in the design you propose).

this should be already accomplished in the current schema via the `batchlib_version` attribute; we could then either make the (`batchlib_version`, `plate_name`) pair unique within the collection (by creating a unique index), i.e. a single result per a given plate and given batchlib version, or we can just replace the document with a given (`batchlib_version`, `plate_name`) to allow re-computation of the pipeline

> Also for 1., we will have multiple result_tables: We will at least have 1 image table and 1 well table, see also #59. There will also be object based tables (1 for each image), but I am not quite sure yet if these need to go into the database. In addition, @imagirom might run additional kinds of analysis that generate different versions of the tables (but this could also be handled by pushing this to different antibody-assays entries, see previous point).

sure we could put as many nested documents as we want in there, e.g. `per_plate_results`, `per_well_results`, `per_object_results`

@tischi:
> I am not sure you cover this already in above schema, but I think for the antibody-assay we may need those granularities

I think the 3rd point discussed above covers this

> For example, the QC can be image and well based...

for this I'd indeed change a schema of `immuno-assay-metadata` to reflect this. Currently there is:
```
{
name: SomePlateName
images: [
  {name: 'img-name', ...}, ...
]
...
}
```
we could nest `images` under `wells` like this:
```
{
name: SomePlateName
wells: [
   {
     name: WellName,
     outlier-status: '....',
     images: [{name: 'img-name', ...}, ]
   },
  ...
]

...
}

```

**Comment by constantinpape** [comment]
Very good!

I just thought of one more thing:
It would also be nice to somehow keep track of associated issues for the images.

**Comment by wolny** [comment]
Sounds good. I don't think issues deserve a dedicated collection in the DB for now, so let's reflect this in the additional attribute for the image called `issue_url`. We'll make additional call to MongoDB to create this image attribute, when the issue is create from the Plate Viewer.

**Comment by wolny** [comment]
Ok, so let's wait for that initial schema to sink in. 
The way I'll proceed with it:
1. Write the migration script *only* for the `immuno-assay-metadata`
2. Write the API for batchlib, plate viewer, outlier app and populate `immuno-assay-analysis-results` on the go. It's easier to just rerun the analysis on all of the plates and no need to spend time on additional migration for the current results.

**Comment by constantinpape** [comment]
> Ok, so let's wait for that initial schema to sink in.
> The way I'll proceed with it:
> 
>     1. Write the migration script _only_ for the `immuno-assay-metadata`
> 
>     2. Write the API for batchlib, plate viewer, outlier app and populate `immuno-assay-analysis-results` on the go. It's easier to just rerun the analysis on all of the plates. No need to spend time on additional migration script for the results we currently have.

Sounds good overall. 

Re 2., I would like to eventually do this as follows:
First save results locally in the hdf5 table layout discussed [here](https://github.com/hci-unihd/batchlib/issues/59#issuecomment-620714701) and [here](https://github.com/hci-unihd/batchlib/issues/52#issuecomment-620609141).
Then have some final `DatabaseJob` that parses these tables and writes them to the DB.
This way, the analysis can still run through even if the database is currently not available and the database is kept optional in general.

**Comment by wolny** [comment]
> Then have some final DatabaseJob that parses these tables and writes them to the DB.
This way, the analysis can still run through even if the database is currently not available and the database is kept optional in general.

that was exactly what I was thinking as well!

**Comment by constantinpape** [comment]
Forgot a very important thing: Vibor also has results from the ELISA test and Schnelltest for some of the plates. These should def. go into the metadata as well if available.
