### ISSUE TITLE
well, image and objects table

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#59]
cc @wolny @imagirom 

Just had a chat with @constantinpape and we think we need to properly represent three granularities:
- wells
- images
- cells

and have a table (and db entry) for each of them.

I was hoping we can get around the well table and just add numbers to the image table (same value for all images in the same well), but since the main result of our analysis is in fact one number per well I think we should probably do this properly.

Any opinions?

**Comment by constantinpape** [comment]
In the disc representation, we would store these tables as follows:

For `wells` and `images`, there will be a file `<PLATE_NAME>_tables.h5` (or so) in the folder,
with the following layout:
```
wells/
 default   (this is the default table that will be loaded by the plateViewer, can also be a reference)
 ...           (can contain an arbitrary number of other well tables for different analysis methods)
images/
  same layout as for wells, but containing the image level attributes
```

the `cells` or object tables will be stored in the image hdf5 files and contain cell level attributes (basically what Roman is computing already and storing in the pickle files)

all tables will have [this layout](https://github.com/hci-unihd/batchlib/issues/52#issuecomment-620609141).

**Comment by constantinpape** [comment]
This is all implemented now. @tischi feel free to reopen if you find any bugs.
