### ISSUE TITLE
Rename semantic channels?

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#68]
@tischi brought up that we may want to rename the semantic channels:
1. the `serum` channel should always be called `serum_IgX`, also if we only have a single one, to avoid confusion.
2. Rename `marker` to `virus`.

I definitely agree on 1. and don't really mind what's it called for 2. Because there is just a single marker / virus channel there is no real ambiguity, so the name doesn't matter so much.

On our side, we only need to change the channel mapping json to change this.

What do you think @imagirom?

**Comment by imagirom** [comment]
1. I agree, we can simply change that in the `channel_config.json` for those plates.
2. I also don't really mind. I have a slight preference to keep it as `marker`, as that is its name everywhere in the code (and changing it everywhere would take some effort).

**Comment by tischi** [comment]
1. agree
2. let's leave it marker, I would say

**Comment by constantinpape** [comment]
Ok, sounds good.
I will write a script to update the channel mapping to change the `serum` name accordingly later.

**Comment by metavibor** [comment]
1. and 2. - I agree

**Comment by constantinpape** [comment]
>     1. and 2. - I agree

@metavibor for 1., can we assume that what we have called `serum` so far is always `serum_IgG`?
In other words, when you image only one serum channel, is it always IgG?

**Comment by metavibor** [comment]
there was one or two instances when I had only IgA, these were some test situations, in general I will always have two channels - IgG and something else (IgA or IgM)

**Comment by constantinpape** [comment]
> there was one or two instances when I had only IgA, these were some test situations, in general I will always have two channels - IgG and something else (IgA or IgM)

Ok, I see. Then we need to be a bit more careful with this.
I will check all the plates later and see for which ones we are not sure and then ask you to fill in the information for these ;).

**Comment by metavibor** [comment]
sounds good

**Comment by constantinpape** [comment]
Ok, I had a look into this now, and I am a bit confused. In our channel mappings we never have IgM.
Anyway, this is what we have right now `'serum'` means we haven't specified wether it's IgG or IgA):
```
20200406_164555_328 : ['serum']
20200406_210102_953 : ['serum']
20200406_222205_911 : ['serum']
20200410_145132_254 : ['serum']
20200410_172801_461 : ['serum']
20200415_150710_683 : ['serum']
20200417_132123_311 : ['serum_IgG', 'serum_IgA']
20200417_152052_943 : ['serum_IgG', 'serum_IgA']
20200417_172611_193 : ['serum_IgG', 'serum_IgA']
20200417_185943_790 : ['serum_IgG', 'serum_IgA']
20200417_203228_156 : ['serum_IgG', 'serum_IgA']
20200420_152417_316 : ['serum_IgG', 'serum_IgA']
20200420_164920_764 : ['serum_IgG', 'serum_IgA']
plate7rep1_20200426_103425_693 : ['serum_IgG', 'serum_IgA']
plate8rep1_20200425_162127_242 : ['serum_IgG', 'serum_IgA']
plate9rep1_20200430_144438_974 : ['serum_IgG', 'serum_IgA']
plateK10rep1_20200429_122048_065 : ['serum_IgG', 'serum_IgA']
plateK11rep1_20200429_140316_208 : ['serum_IgG', 'serum_IgA']
plateK12rep1_20200430_155932_313 : ['serum_IgG', 'serum_IgA']
plateK13rep1_20200430_175056_461 : ['serum_IgG', 'serum_IgA']
plateK14rep1_20200430_194338_941 : ['serum_IgG', 'serum_IgA']
titration_plate_20200403_154849 : ['serum_IgG']
```
@metavibor could you fill in which type it is for the ones where we only have `'serum'` and check that it's correct for the others? Sorry for the inconvenience.

**Comment by metavibor** [comment]
@constantinpape you did not have a full plate with IgM yet (there have been a few wells where I tested different antibodies), the first plate with IgM was done yesterday and I will upload it tomorrow.
I will look up the missing info now

**Comment by metavibor** [comment]
@constantinpape 
20200406_164555_328 : ['serum IgG']
20200406_210102_953 : ['serum IgG']
20200406_222205_911 : ['serum IgG']
20200410_145132_254 : ['serum IgG']
20200410_172801_461 : ['serum IgA']
20200415_150710_683 : ['serum IgA'] column 1-6 ['serum IgG'] column 7-12
20200417_132123_311 : ['serum_IgG', 'serum_IgA']
20200417_152052_943 : ['serum_IgG', 'serum_IgA']
20200417_172611_193 : ['serum_IgG', 'serum_IgA']
20200417_185943_790 : ['serum_IgG', 'serum_IgA']
20200417_203228_156 : ['serum_IgG', 'serum_IgA']
20200420_152417_316 : ['serum_IgG', 'serum_IgA']
20200420_164920_764 : ['serum_IgG', 'serum_IgA']
plate7rep1_20200426_103425_693 : ['serum_IgG', 'serum_IgA']
plate8rep1_20200425_162127_242 : ['serum_IgG', 'serum_IgA']
plate9rep1_20200430_144438_974 : ['serum_IgG', 'serum_IgA']
plateK10rep1_20200429_122048_065 : ['serum_IgG', 'serum_IgA']
plateK11rep1_20200429_140316_208 : ['serum_IgG', 'serum_IgA']
plateK12rep1_20200430_155932_313 : ['serum_IgG', 'serum_IgA']
plateK13rep1_20200430_175056_461 : ['serum_IgG', 'serum_IgA']
plateK14rep1_20200430_194338_941 : ['serum_IgG', 'serum_IgA']
titration_plate_20200403_154849 : ['serum_IgG']

**Comment by constantinpape** [comment]
Thanks @metavibor. I will update our channel mappings based on this now.

**Comment by constantinpape** [comment]
>  20200415_150710_683 : ['serum_IgA'] column 1-6 ['serum_IgG'] column 7-12

Does that mean that some of the wells have IgA, some have IgG?
If that's so, we cannot really deal with this yet.
How common is this, should we adapt our code to make it work for this case?

**Comment by metavibor** [comment]
yes that is correct but that is the case only for that plate and occasional well in other plates... this will not happen on any new plates... don't bother adapting the code for this isolated case. Just use "IgG" labelling in this case and I will make a note of this so later we know this plate is a special case

**Comment by constantinpape** [comment]
Thanks for the clarification.
I have updated the channel mappings now and also made a note about the plate with mixed IgG/IgA.
