### ISSUE TITLE
Number of cells column

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#70]
I think we should add a column "n_cells" in the image (and well) table.
This is an absolute standard readout for all HTM assays.
Also, biologically it is very important to check in the end whether our score shows any (surprising) correlation with cell density.

**Comment by constantinpape** [comment]
> I think we should add a column "n_cells" in the image (and well) table.

You can already see it on the fly as `n_infected + n_control`. But I agree, it doesn't hurt to have it as a proper column.

**Comment by constantinpape** [comment]
Either Roman or me can do this, after we discuss how to treat the slightly more involved #69

**Comment by tischi** [comment]
> You can already see it on the fly as `n_infected` + `n_control`.

I know, but trust me, **the very first thing** people in HTM microscopy would like to do is `[ Color by Column > Number of cells ]` to check wether they managed to evenly seed the cells in the plate.

**Comment by constantinpape** [comment]
> I know, but trust me, **the very first thing** people in HTM microscopy would like to do is `[ Color by Column > Number of cells ]` to check wether they managed to evenly seed the cells in the plate.

Yes, makes total sense. Roman will add it later after implementing a few of the more fundemental issues.

**Comment by imagirom** [comment]
Added in f951d208c2e45e2c7b9a4b4712880411beeb616d. The column name is `n_cells`.
