### ISSUE TITLE
Fraction infected column

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#71]
I know it is redundant, but a "fraction_infected" column would be good to have because this really is one of the main points of our assay. The closer this is to 0.5 the better the assay. Plates or wells where this number is too close to 1.0 may even fail QC...

**Comment by constantinpape** [comment]
Sure, doesn't hurt to add it. Will add it after figuring out what to do with #69.

**Comment by imagirom** [comment]
Added in f8bd8890db2718ec5ae134aebe85afadfeb4d34c. The column name is `fraction_infected`
