### ISSUE TITLE
Refactor all_plots function

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#72]
see https://github.com/hci-unihd/batchlib/blob/workflows/batchlib/util/plate_visualizations.py#L239-L240

**Comment by imagirom** [comment]
I made `all_plots` compatible with the per-well tables in db89240f39cf08e2cb97b7e15f4e21e6c2810467. Currently `np.nan`s are screwing up the colorbar for many plots, I will figure that out later.

**Comment by constantinpape** [comment]
@Steffen-Wolf @imagirom is this fixed now in fdfbf3cdccf40edd800186ddab351889b455791d?

**Comment by imagirom** [comment]
Yes, that should be the case
