### ISSUE TITLE
Cell feature column: Number of pixels infected vs. control

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#75]
@imagirom @constantinpape
I think for the assay characterisation it would be important to measure (already for the upcoming publication) whether the infected and control cells have the same size. Of course we cannot really measure their volume, so the best we can do is measure the number of pixels of the segments. Could this be added to the cell/ image/ well tables for both infected and control cells?

**Comment by constantinpape** [comment]
Yes, I think we can add it.
However, I think right now we are not calculating the cell segment pixel sizes (correct me if I am wrong @imagirom). We should def. add it, because we will need it for the QC as well.

@imagirom we could just use `np.unique(return_counts=True)` to compute it, OR use [regionprops](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops) if we want to measure some more morphological properties.

**Comment by imagirom** [comment]
The cell size is already measured, the key in the cell tables is `sizes`.

**Comment by imagirom** [comment]
@tischi when you say add to the image / well tables, do you mean the average and median size of infected and control cells?

@constantinpape I think regionprops could also be useful for cell-level qc. Do you know how efficient it is?

**Comment by constantinpape** [comment]
> @constantinpape I think regionprops could also be useful for cell-level qc. Do you know how efficient it is?

I am not really sure. I have used it before, but under very different circumstances, where the overhead of running it was negligable, because the segmentation methods were much more involved.
Let's leave it out for now and reconsider if we really need something in there for the cell qc.

**Comment by constantinpape** [comment]
> @tischi when you say add to the image / well tables, do you mean the average and median size of infected and control cells?

@tischi could you answer this?

**Comment by tischi** [comment]
I think it would be great to have:

1. cell_size_median_infected_per_image
2. cell_size_median_control_per_image
3. cell_size_median_infected_per_well
4. cell_size_median_control_per_well

You could also add the mean, but I think median could be enough.

**Comment by imagirom** [comment]
@tischi Ok, for now I will add cell_size_median_infected and cell_size_median_control to image and well tables. Is that way fine or do you really want me to duplicate the per-well information in the per-image table?

**Comment by imagirom** [comment]
Implemented in dce1d1dbdc90d4d45dfad3b16186b0837bb05c88.

**Comment by constantinpape** [comment]
> @tischi Ok, for now I will add cell_size_median_infected and cell_size_median_control to image and well tables. Is that way fine or do you really want me to duplicate the per-well information in the per-image table?

That's the way it should be; the image table should not contain duplicate per will information.

**Comment by tischi** [comment]
agreed!
