### ISSUE TITLE
Strings loaded from h5 tables prefixed with b' and suffixed with '

### ISSUE THREAD

**Issue by imagirom** [hci-unihd/batchlib#79]
I observed this here: https://github.com/hci-unihd/batchlib/commit/fc10767c9ee03d676f7cae9243303530c00dcd86#diff-1523659049987d3e5aa788721dee0d84R669-R670 
and worked around it for the well plots here https://github.com/hci-unihd/batchlib/commit/db89240f39cf08e2cb97b7e15f4e21e6c2810467#diff-415d4435c76db06592ddcba790842cb7R270 (e.g. well name `"A01"` is loaded as `"b'A01'"`)

**Comment by constantinpape** [comment]
I think this is fixed now. If not, feel free to reopen.
