### ISSUE TITLE
Bug in csv image table

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#82]
In `plateK14rep1_20200430_194338_941_IgG` there was a `\t` missing between `well_cell_based_score` and `num_cells` in the csv table.
I added it there manually and re-saved the table, but then there were more column names (35) than values (34). So probably, in addition a whole column is missing?

**Comment by constantinpape** [comment]
Ok, weird.
We don't write the csv tables any more, and I don't think this can happen in the new hdf5 tables (there are several checks that number of columns and column names agree), but I will leave this open until we checked.

**Comment by constantinpape** [comment]
I think this is solved.
