### ISSUE TITLE
Hdf5 based tables missing

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#83]
For the latest analyses the hdf5 based tables seem to be missing, but there are only the csv based ones. Is it on purpose?

**Comment by constantinpape** [comment]
@imagirom always ran analysis with the more stable master version of the analysis; and I only merged #51, which writes the hdf5 tables yesterday evening.
So yes, this is expected. I will try to rerun everything with the newer version at EMBL today.
