### ISSUE TITLE
How do we handle different analysis results in same folder?

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#84]
In #51 @imagirom has updated the pipeline s.t. results for different versions of the analysis (e.g.  from running segmentation or intensity accumulation on different channels), can be stored in the same image h5 file.

However for the hdf5 file that holds the image and well table, he is writing different files per analysis result with a different identifier in the name now.

We should discuss if we want to keep it this way, or if we also want to only have one file and then differerent internal paths for the analysis results in there. Obviously, this has implications for the
viewer and the database migration.

cc @imagirom @tischi @wolny

**Comment by wolny** [comment]
From the DB point of view it doesn't really matter: having different files per analysis, or nesting analysis results withing a single file will result in the same document stored in DB (in terms of schema), only the way we create this document (i.e. from single or multiple files) will be different.

Let's focus the discussion on how we deal with it in the viewer.

**Comment by tischi** [comment]
Can we discuss this during some zoom meeting on Monday?

**Comment by constantinpape** [comment]
We discussed this via zoom now and came to the following conclusion:
- everything should be in a single table file
- the different analysis results are then in separate table keys in that file
- after everything went through, we merge the relevant results into single tables `images/default` and `wells/default`.

@imagirom can you take care of adapting the table saving logic?
I can work on the table merging.

**Comment by imagirom** [comment]
@constantinpape Yes, I can implement the saving of tables in a single file.
For the merging, I think as long as we only want to do it in the multiple serum channel setting, we might be able to get away with simply replacing `serum` by `serum_IgA` etc.

**Comment by wolny** [comment]
Ok, so after merging the table structure will be the same, so in theory there is no need to change the DB job. But please let me know when this is done and I'll test the DB integration.

**Comment by constantinpape** [comment]
@wolny yes, will do

**Comment by tischi** [comment]
You could even replace `serum` just with, e.g., `IgA` to be more concise.

**Comment by constantinpape** [comment]
@imagirom has implemented his part in #92 now, I will do the table merging later.

**Comment by constantinpape** [comment]
Implementing the table merging in #95.
@tischi I haven't done any of the renaming yet, but this is refactored into functions:
https://github.com/hci-unihd/batchlib/blob/merge-tables/batchlib/analysis/merge_tables.py#L58-L63
I will compute a test output with the current version now and then we can look into how we rename columns later.

**Comment by constantinpape** [comment]
Implemented in #95
