### ISSUE TITLE
Integrate PlateViewer with the DB

### ISSUE THREAD

**Issue by wolny** [hci-unihd/batchlib#89]
Implement the following functionalities:
1. Setting QC flag on the image/well/plate and saving it into db.
2. Saving/Loading the manual assessment of the well to/from DB. Vibor will provide us with labels which 'likely positive'/'likely negative' for the wells, and we can use the plate viewer to load the plate, right-click on the well and choose 'definitely positive'/'definitely negative'.
3. When creating an issue for a given image/well/plate, we should also make a call to the DB to reflect this fact.

@tischi I've created this issue just to keep track of things. I'm done with the Python side of all things DB and have some java code snippets for aforementioned functionalities, so let's bring it together with your interfaces at some point.

**Comment by tischi** [comment]
ok, we could work on it tomorrow together. do you have time?

**Comment by wolny** [comment]
tomorrow would work for me only in the in the evening unfortunately, but I've created a quick API for you already: https://github.com/embl-cba/fiji-plugin-plateViewer/pull/27 :)

**Comment by tischi** [comment]
ok. I can try it out. thanks!
Is the DB up and running?
Do I have to be in EMBL intranet?

**Comment by constantinpape** [comment]
> ok. I can try it out. thanks!
> Is the DB up and running?
> Do I have to be in EMBL intranet?

I just talked to @wolny and we have a preliminary version up and running.
I will try to create a DB entry for one of the plates later and let you know when it's there.

**Comment by wolny** [comment]
Hey @tischi,

> Is the DB up and running?

yes, I've setup a trial DB at EMBL, here's the info:
```
--db_username covid19
--db_password <secret>
--db_host vm-kreshuk08.embl.de
--db_port 27017
--db_name covid
```
I'll send you the password on slack.

> Do I have to be in EMBL intranet?

yes, you need to be inside the EMBL VPN, so that you can reach `vm-kreshuk08.embl.de` VM.

**Comment by wolny** [comment]
@tischi, @constantinpape will run an analysis workflow on a sample plates to populate the DB, so that  you could test it (like he said already)

**Comment by tischi** [comment]
@wolny 
seems to work. 

1. However your demo code crashes. I guess because the "test-cell-analysis" plate is not there?
2. I am not sure about the name of this function `getManualAssessment()`, we should clarify with Vibor what this really is. In my code I just called it `getAnnotation()`

**Comment by wolny** [comment]
@tischi 
1. yes sure :) we need to  use the plates which were added when @constantinpape run the analysis today; as of now we have: `titration_plate_20200403_154849` and `20200410_172801_461` in there
2. I'm totally fine with calling it `getAnnotation()`; the field in db is called `manual_assessment`, but I can change it to `annotation` in the next version of the schema

don't be afraid to break stuff, it's a development db :)

**Comment by tischi** [comment]
@wolny @constantinpape 
Based on the recent zoom meeting I think the DB should:
1. Setting QC flag on the image/well/plate and saving it into db (read/write).
1. Loading a patient `cohort_id` from DB (read only). Vibor will provide us with these IDs.
1. When creating an issue for a given image/well/plate, we should also make a call to the DB to reflect this fact (read/write).

Note that the second item changed. The "manual assessment" is gone, but there is the __read only__ cohort ID.

@metavibor In the database, should there be maybe also be a column, called `sample_id`? The difference, as far as I understood it, to the `cohort_id` could be that a `sample_id` would allow to trace back the patient, whereas several patients could have the same `cohort_id`?!

**Comment by metavibor** [comment]
I think having something like "sample_id" will be useful, for example for longitudinal studies we will have the same person but serum collected on different days... Than "sample_id" can be changed to reflect that...in "cohort_id" is already the info which allows tracing back the patient

**Comment by tischi** [comment]
> in "cohort_id" is already the info which allows tracing back the patient

This I do not get, I thought we will have different people belonging to the same cohort?

**Comment by tischi** [comment]
...@metavibor, in other words: what we need in the database is a column, where there is information what score we should expect, e.g. `positive_pcr` or `before_2018`. This does not have to be called like this explicitly.  Anyway, I was thinking that on one plate _several wells_ should be expected  to have the _same_ score, because they come from the _same_ "type" of person.

**Comment by metavibor** [comment]
"cohort id" goes something like this "P35", P means "plasma donor cohort" and 35 is the number of the person.

**Comment by metavibor** [comment]
on plates 1 and 2 half of the plate is filled with PCR positive samples and other half is pre2020 samples

**Comment by tischi** [comment]
@metavibor  
So if we split off the letter (e.g., **P**) from the number (e.g., 35) we have what in a normal biological assay would correspond to the **treatment**, i.e. (**treatment** = **P**)?!

**Comment by metavibor** [comment]
@tischi yes, you can look at it that way if it helps

**Comment by constantinpape** [comment]
@wolny there is still a few things to be done to finish the DB integration:

- [ ] Migrate to the production DB
- [ ] Provide convenient python API so we can use the cohort information for evaluation
- [ ] Add the elisa information, see https://github.com/hci-unihd/batchlib/blob/master/misc/elisa/elisa_assay_results_202005008.xlsx
- [ ] Add the cohort information, see https://github.com/hci-unihd/batchlib/blob/master/misc/cohort_ids/cohort_descriptions.json
- [ ] Figure out connectivity issues, see #105

**Comment by wolny** [comment]
1. Dev db has been migrated into the prod, we just need to make the switch in the batchlib config (see: https://github.com/hci-unihd/batchlib/pull/108). I'd recommend to have two config files one for dev and one for prod. Testing PRs etc. should be done with dev config and running the analysis on the new plates should be done on the prod db.
2. This was done already (see: https://github.com/hci-unihd/batchlib/blob/master/batchlib/mongo/plate_metadata_repository.py). We can extend this API if necessary when writing the evaluation code.
3. In progress (I'll run it on the prod db as well when this is ready)
4. This was done already (see: https://github.com/hci-unihd/batchlib/blob/master/batchlib/mongo/import_cohort_ids.py#L57) 6. and is stored in `cohort-descriptions` collection. See also the DB readme for the schema description: https://github.com/hci-unihd/batchlib/blob/master/batchlib/mongo/README.md#schema-description
5. In progress...
6. I cannot reproduce this issue. It's a `SocketTimeoutException`, so most likely there was an issue with the VPN.

**Comment by tischi** [comment]
> I cannot reproduce this issue. It's a SocketTimeoutException, so most likely there was an issue with the VPN.

Could be, sometimes my internet in general becomes super slow and I need to restart everything, computer, router, ... 
I do not understand what happens there.

**Comment by wolny** [comment]
Initially I thought it might be because of the document size: our result docs are quite bulky now, e.g. if you run:
```
mongo covid --host vm-kreshuk08.embl.de --port 27017 -u "covid19" --authenticationDatabase "covid" --eval 'db["immuno-assay-analysis-results"].find({plate_name: "plateT3rep1_20200509_152617_891"}).pretty()' -p >> result.json
```
the resulting JSON is 18MB. But then again even if your internet is very slow it shouldn't be `SocketTimeoutException` cause you're connection is working but is very slow.

**Comment by constantinpape** [comment]
I think most of the things discussed in this issue are implemented.
I will close it. Let's make separate issues for other problems with the DB.
