### ISSUE TITLE
Analysis columns visibility

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#91]
@imagirom @constantinpape 

I would propose to, for now:

1. **only show** `q0.5` based measurements (_not show_ other  `q0.*` based ones)
2. do _not show_ `mean_of_*` but **only show** `q0.5_of_*` based columns

What do you think?

**Comment by constantinpape** [comment]
Sounds reasonable to me. If @imagirom agrees, I can implement it.

**Comment by imagirom** [comment]
@constantinpape Yes, sounds good to me as well. If we do want to look at it at some point, we can just change the viewer settings in the h5, right?

**Comment by constantinpape** [comment]
> Yes, sounds good to me as well.

Ok, I will change it tomorrow.

> If we do want to look at it at some point, we can just change the viewer settings in the h5, right?

Yes.
Also, in the long run it would be nice to be able to change it in the viewer, but that doesn't have high priority...

**Comment by constantinpape** [comment]
I am solving this in #95 now by only keeping certain columns in the summary table.
This is implemented here:
https://github.com/hci-unihd/batchlib/blob/merge-tables/batchlib/analysis/merge_tables.py#L40-L56
I will expose this as parameters with reasonable defaults later.
@tischi do you also want to keep the z-score or only the median? Something else?

**Comment by tischi** [comment]
1. I think z-score should stay, could be interesting.
1. What about `site_name` and `well_name`? They are essential.

Otherwise looks fine.

**Comment by constantinpape** [comment]
> * think z-score should stay, could be interesting.
Ok, I will keep it.
> 
> * What about `site_name` and `well_name`? They are essential.
Oh yeah, I think I dropped those now ....
Will fix it later!

**Comment by constantinpape** [comment]
Ok, I am keeping the z-score now and also site and well name.
@tischi here is the newest version:
`/g/kreshuk/data/covid/sandbox/merged_table/plateK12rep1_20200430_155932_313`

**Comment by constantinpape** [comment]
@tischi 
Could you check if you want any other changes to the names or the visible columns?
Here is the newest version:
`/g/kreshuk/data/covid/sandbox/merged_table/plateK12rep1_20200430_155932_313`

**Comment by tischi** [comment]
@constantinpape 
Let's just leave it as is for now. We anyway need to solve this differently, i.e. make columns selectable from the viewer.

**Comment by constantinpape** [comment]
> Let's just leave it as is for now. We anyway need to solve this differently, i.e. make columns selectable from the viewer.

Sounds good. Gonna close this for now then.
